//
// Created by leonhard on 18.08.19.
//
#include <iostream>
#include "../catch.hpp"
#include "../src/wam/bfs_organizer/bfs_organizer.h"

using namespace std;
using namespace wam;

TEST_CASE("p5-0 test") {
    bfs_organizer org;

    org.load_program("test_src/p5-0.pl");

    SECTION("[]") {
        org.load_query("lvonM([]).");
        auto answer = org.get_answer();
        REQUIRE(answer.has_value());
    }
    SECTION("[a]") {
        org.load_query("lvonM([a]).");
        auto answer = org.get_answer();
        REQUIRE(answer.has_value());
    }
    SECTION("lVonM") {
        org.load_query("lvonM(Z).");

        auto answer = org.get_answer();
        REQUIRE(answer.has_value());
        while (answer) {
            for (auto &elem : *answer) {
//                cout << elem << endl;
            }
            break;
            answer = org.get_answer();
        }
//        [Z / []]
//        [Z / [nix]]
//        [Z / [b]]
//        [Z / [a]]
//        [Z / [nix,b]]
//        [Z / [nix,a]]
//        [Z / [b,b]]
//        [Z / [b,nix,b]]
//        [Z / [a,a]]
//        [Z / [a,nix,a]]
//        [Z / [nix,b,b]]
//        [Z / [nix,b,nix,b]]
//        [Z / [nix,a,a]]
//        [Z / [nix,a,nix,a]]
//        [Z / [b,b,b]]
//        [Z / [b,a,b]]
//        [Z / [b,nix,b,b]]
//        [Z / [b,nix,a,b]]
//        [Z / [a,b,a]]
//        [Z / [a,a,a]]
//        [Z / [a,nix,b,a]]
//        [Z / [a,nix,a,a]]
//        [Z / [nix,b,b,b]]
//        [Z / [nix,b,a,b]]
//        [Z / [nix,b,nix,b,b]]
//        [Z / [nix,b,nix,a,b]]
//        [Z / [nix,a,b,a]]
//        [Z / [nix,a,a,a]]
//        [Z / [nix,a,nix,b,a]]
//        [Z / [nix,a,nix,a,a]]
//        [Z / [b,b,b,b]]
//        [Z / [b,b,nix,b,b]]
//        [Z / [b,a,a,b]]
//        [Z / [b,a,nix,a,b]]
//        [Z / [b,nix,b,b,b]]
//        [Z / [b,nix,b,nix,b,b]]
//        [Z / [b,nix,a,a,b]]
//        [Z / [b,nix,a,nix,a,b]]
//        [Z / [a,b,b,a]]
//        [Z / [a,b,nix,b,a]]
//        [Z / [a,a,a,a]]
//        [Z / [a,a,nix,a,a]]
//        [Z / [a,nix,b,b,a]]
//        [Z / [a,nix,b,nix,b,a]]
//        [Z / [a,nix,a,a,a]]
//        [Z / [a,nix,a,nix,a,a]]
//        [Z / [nix,b,b,b,b]]
//        [Z / [nix,b,b,nix,b,b]]
//        [Z / [nix,b,a,a,b]]
//        [Z / [nix,b,a,nix,a,b]]
//        [Z / [nix,b,nix,b,b,b]]
//        [Z / [nix,b,nix,b,nix,b,b]]
//        [Z / [nix,b,nix,a,a,b]]
//        [Z / [nix,b,nix,a,nix,a,b]]
//        [Z / [nix,a,b,b,a]]
//        [Z / [nix,a,b,nix,b,a]]
//        [Z / [nix,a,a,a,a]]
//        [Z / [nix,a,a,nix,a,a]]
//        [Z / [nix,a,nix,b,b,a]]
//        [Z / [nix,a,nix,b,nix,b,a]]
//        [Z / [nix,a,nix,a,a,a]]
//        [Z / [nix,a,nix,a,nix,a,a]]
//        [Z / [b,b,b,b,b]]
//        [Z / [b,b,a,b,b]]
//        [Z / [b,b,nix,b,b,b]]
//        [Z / [b,b,nix,a,b,b]]
//        [Z / [b,a,b,a,b]]
//        [Z / [b,a,a,a,b]]
//        [Z / [b,a,nix,b,a,b]]
//        [Z / [b,a,nix,a,a,b]]
//        [Z / [b,nix,b,b,b,b]]
//        [Z / [b,nix,b,a,b,b]]
//        [Z / [b,nix,b,nix,b,b,b]]
//        [Z / [b,nix,b,nix,a,b,b]]
//        [Z / [b,nix,a,b,a,b]]
//        [Z / [b,nix,a,a,a,b]]
//        [Z / [b,nix,a,nix,b,a,b]]
//        [Z / [b,nix,a,nix,a,a,b]]
//        [Z / [a,b,b,b,a]]
//        [Z / [a,b,a,b,a]]
//        [Z / [a,b,nix,b,b,a]]
//        [Z / [a,b,nix,a,b,a]]
//        [Z / [a,a,b,a,a]]
//        [Z / [a,a,a,a,a]]
//        [Z / [a,a,nix,b,a,a]]
//        [Z / [a,a,nix,a,a,a]]
//        [Z / [a,nix,b,b,b,a]]
//        [Z / [a,nix,b,a,b,a]]
//        [Z / [a,nix,b,nix,b,b,a]]
//        [Z / [a,nix,b,nix,a,b,a]]
//        [Z / [a,nix,a,b,a,a]]
//        [Z / [a,nix,a,a,a,a]]
//        [Z / [a,nix,a,nix,b,a,a]]
//        [Z / [a,nix,a,nix,a,a,a]]
//        [Z / [nix,b,b,b,b,b]]
//        [Z / [nix,b,b,a,b,b]]
//        [Z / [nix,b,b,nix,b,b,b]]
//        [Z / [nix,b,b,nix,a,b,b]]
//        [Z / [nix,b,a,b,a,b]]
//        [Z / [nix,b,a,a,a,b]]
//        [Z / [nix,b,a,nix,b,a,b]]
//        [Z / [nix,b,a,nix,a,a,b]]
//        [Z / [nix,b,nix,b,b,b,b]]
//        [Z / [nix,b,nix,b,a,b,b]]
//        [Z / [nix,b,nix,b,nix,b,b,b]]
//        [Z / [nix,b,nix,b,nix,a,b,b]]
//        [Z / [nix,b,nix,a,b,a,b]]
//        [Z / [nix,b,nix,a,a,a,b]]
//        [Z / [nix,b,nix,a,nix,b,a,b]]
//        [Z / [nix,b,nix,a,nix,a,a,b]]
//        [Z / [nix,a,b,b,b,a]]
//        [Z / [nix,a,b,a,b,a]]
//        [Z / [nix,a,b,nix,b,b,a]]
//        [Z / [nix,a,b,nix,a,b,a]]
//        [Z / [nix,a,a,b,a,a]]
//        [Z / [nix,a,a,a,a,a]]
//        [Z / [nix,a,a,nix,b,a,a]]
//        [Z / [nix,a,a,nix,a,a,a]]
//        [Z / [nix,a,nix,b,b,b,a]]
//        [Z / [nix,a,nix,b,a,b,a]]
//        [Z / [nix,a,nix,b,nix,b,b,a]]
//        [Z / [nix,a,nix,b,nix,a,b,a]]
//        [Z / [nix,a,nix,a,b,a,a]]
//        [Z / [nix,a,nix,a,a,a,a]]
//        [Z / [nix,a,nix,a,nix,b,a,a]]
//        [Z / [nix,a,nix,a,nix,a,a,a]]
//        [Z / [b,b,b,b,b,b]]
//        [Z / [b,b,b,nix,b,b,b]]
//        [Z / [b,b,a,a,b,b]]
//        [Z / [b,b,a,nix,a,b,b]]
//        [Z / [b,b,nix,b,b,b,b]]
//        [Z / [b,b,nix,b,nix,b,b,b]]
//        [Z / [b,b,nix,a,a,b,b]]
//        [Z / [b,b,nix,a,nix,a,b,b]]
//        [Z / [b,a,b,b,a,b]]
//        [Z / [b,a,b,nix,b,a,b]]
//        [Z / [b,a,a,a,a,b]]
//        [Z / [b,a,a,nix,a,a,b]]
//        [Z / [b,a,nix,b,b,a,b]]
//        [Z / [b,a,nix,b,nix,b,a,b]]
//        [Z / [b,a,nix,a,a,a,b]]
//        [Z / [b,a,nix,a,nix,a,a,b]]
//        [Z / [b,nix,b,b,b,b,b]]
//        [Z / [b,nix,b,b,nix,b,b,b]]
//        [Z / [b,nix,b,a,a,b,b]]
//        [Z / [b,nix,b,a,nix,a,b,b]]
//        [Z / [b,nix,b,nix,b,b,b,b]]
//        [Z / [b,nix,b,nix,b,nix,b,b,b]]
//        [Z / [b,nix,b,nix,a,a,b,b]]
//        [Z / [b,nix,b,nix,a,nix,a,b,b]]
//        [Z / [b,nix,a,b,b,a,b]]
//        [Z / [b,nix,a,b,nix,b,a,b]]
//        [Z / [b,nix,a,a,a,a,b]]
//        [Z / [b,nix,a,a,nix,a,a,b]]
//        [Z / [b,nix,a,nix,b,b,a,b]]
//        [Z / [b,nix,a,nix,b,nix,b,a,b]]
//        [Z / [b,nix,a,nix,a,a,a,b]]
//        [Z / [b,nix,a,nix,a,nix,a,a,b]]
//        [Z / [a,b,b,b,b,a]]
//        [Z / [a,b,b,nix,b,b,a]]
//        [Z / [a,b,a,a,b,a]]
//        [Z / [a,b,a,nix,a,b,a]]
//        [Z / [a,b,nix,b,b,b,a]]
//        [Z / [a,b,nix,b,nix,b,b,a]]
//        [Z / [a,b,nix,a,a,b,a]]
//        [Z / [a,b,nix,a,nix,a,b,a]]
//        [Z / [a,a,b,b,a,a]]
//        [Z / [a,a,b,nix,b,a,a]]
//        [Z / [a,a,a,a,a,a]]
//        [Z / [a,a,a,nix,a,a,a]]
//        [Z / [a,a,nix,b,b,a,a]]
//        [Z / [a,a,nix,b,nix,b,a,a]]
//        [Z / [a,a,nix,a,a,a,a]]
//        [Z / [a,a,nix,a,nix,a,a,a]]
//        [Z / [a,nix,b,b,b,b,a]]
//        [Z / [a,nix,b,b,nix,b,b,a]]
//        [Z / [a,nix,b,a,a,b,a]]
//        [Z / [a,nix,b,a,nix,a,b,a]]
//        [Z / [a,nix,b,nix,b,b,b,a]]
//        [Z / [a,nix,b,nix,b,nix,b,b,a]]
//        [Z / [a,nix,b,nix,a,a,b,a]]
//        [Z / [a,nix,b,nix,a,nix,a,b,a]]
//        [Z / [a,nix,a,b,b,a,a]]
//        [Z / [a,nix,a,b,nix,b,a,a]]
//        [Z / [a,nix,a,a,a,a,a]]
//        [Z / [a,nix,a,a,nix,a,a,a]]
//        [Z / [a,nix,a,nix,b,b,a,a]]
//        [Z / [a,nix,a,nix,b,nix,b,a,a]]
//        [Z / [a,nix,a,nix,a,a,a,a]]
//        [Z / [a,nix,a,nix,a,nix,a,a,a]]
//        [Z / [nix,b,b,b,b,b,b]]
//        [Z / [nix,b,b,b,nix,b,b,b]]
//        [Z / [nix,b,b,a,a,b,b]]
//        [Z / [nix,b,b,a,nix,a,b,b]]
//        [Z / [nix,b,b,nix,b,b,b,b]]
//        [Z / [nix,b,b,nix,b,nix,b,b,b]]
//        [Z / [nix,b,b,nix,a,a,b,b]]
//        [Z / [nix,b,b,nix,a,nix,a,b,b]]
//        [Z / [nix,b,a,b,b,a,b]]
//        [Z / [nix,b,a,b,nix,b,a,b]]
//        [Z / [nix,b,a,a,a,a,b]]
//        [Z / [nix,b,a,a,nix,a,a,b]]
//        [Z / [nix,b,a,nix,b,b,a,b]]
//        [Z / [nix,b,a,nix,b,nix,b,a,b]]
//        [Z / [nix,b,a,nix,a,a,a,b]]
//        [Z / [nix,b,a,nix,a,nix,a,a,b]]
//        [Z / [nix,b,nix,b,b,b,b,b]]
//        [Z / [nix,b,nix,b,b,nix,b,b,b]]
//        [Z / [nix,b,nix,b,a,a,b,b]]
//        [Z / [nix,b,nix,b,a,nix,a,b,b]]
//        [Z / [nix,b,nix,b,nix,b,b,b,b]]
//        [Z / [nix,b,nix,b,nix,b,nix,b,b,b]]
//        [Z / [nix,b,nix,b,nix,a,a,b,b]]
//        [Z / [nix,b,nix,b,nix,a,nix,a,b,b]]
//        [Z / [nix,b,nix,a,b,b,a,b]]
//        [Z / [nix,b,nix,a,b,nix,b,a,b]]
//        [Z / [nix,b,nix,a,a,a,a,b]]
//        [Z / [nix,b,nix,a,a,nix,a,a,b]]
//        [Z / [nix,b,nix,a,nix,b,b,a,b]]
//        [Z / [nix,b,nix,a,nix,b,nix,b,a,b]]
//        [Z / [nix,b,nix,a,nix,a,a,a,b]]
//        [Z / [nix,b,nix,a,nix,a,nix,a,a,b]]
//        [Z / [nix,a,b,b,b,b,a]]
//        [Z / [nix,a,b,b,nix,b,b,a]]
//        [Z / [nix,a,b,a,a,b,a]]
//        [Z / [nix,a,b,a,nix,a,b,a]]
//        [Z / [nix,a,b,nix,b,b,b,a]]
//        [Z / [nix,a,b,nix,b,nix,b,b,a]]
//        [Z / [nix,a,b,nix,a,a,b,a]]
//        [Z / [nix,a,b,nix,a,nix,a,b,a]]
//        [Z / [nix,a,a,b,b,a,a]]
//        [Z / [nix,a,a,b,nix,b,a,a]]
//        [Z / [nix,a,a,a,a,a,a]]
//        [Z / [nix,a,a,a,nix,a,a,a]]
//        [Z / [nix,a,a,nix,b,b,a,a]]
//        [Z / [nix,a,a,nix,b,nix,b,a,a]]
//        [Z / [nix,a,a,nix,a,a,a,a]]
//        [Z / [nix,a,a,nix,a,nix,a,a,a]]
//        [Z / [nix,a,nix,b,b,b,b,a]]
//        [Z / [nix,a,nix,b,b,nix,b,b,a]]
//        [Z / [nix,a,nix,b,a,a,b,a]]
//        [Z / [nix,a,nix,b,a,nix,a,b,a]]
//        [Z / [nix,a,nix,b,nix,b,b,b,a]]
//        [Z / [nix,a,nix,b,nix,b,nix,b,b,a]]
//        [Z / [nix,a,nix,b,nix,a,a,b,a]]
//        [Z / [nix,a,nix,b,nix,a,nix,a,b,a]]
//        [Z / [nix,a,nix,a,b,b,a,a]]
//        [Z / [nix,a,nix,a,b,nix,b,a,a]]
//        [Z / [nix,a,nix,a,a,a,a,a]]
//        [Z / [nix,a,nix,a,a,nix,a,a,a]]
//        [Z / [nix,a,nix,a,nix,b,b,a,a]]
//        [Z / [nix,a,nix,a,nix,b,nix,b,a,a]]
//        [Z / [nix,a,nix,a,nix,a,a,a,a]]
//        [Z / [nix,a,nix,a,nix,a,nix,a,a,a]]
//        [Z / [b,b,b,b,b,b,b]]
//        [Z / [b,b,b,a,b,b,b]]
//        [Z / [b,b,b,nix,b,b,b,b]]
//        [Z / [b,b,b,nix,a,b,b,b]]
//        [Z / [b,b,a,b,a,b,b]]
//        [Z / [b,b,a,a,a,b,b]]
//        [Z / [b,b,a,nix,b,a,b,b]]
//        [Z / [b,b,a,nix,a,a,b,b]]
//        [Z / [b,b,nix,b,b,b,b,b]]
//        [Z / [b,b,nix,b,a,b,b,b]]
    }

}



